### ISSUE TITLE
Functionality explanation

### ISSUE THREAD

**Issue by SolitudeSF** [laelath/kakoune-show-matching-insert#1]
Its absolutely unclear what this plugin does, even after installing it. Some screenshots or more detailed explanation would be great.

**Comment by basbebe** [comment]
+1

I have this in my `kakrc`:
```sh
plug 'laelath/kakoune-show-matching-insert' %{
    add-highlighter global/ ranges show_matching_insert
}
```

and this doesn't seem to do anything

**Comment by laelath** [comment]
Sorry for not addressing this for a while, I updated the description to try to be more explicit about what this does.
